<a href="https://colab.research.google.com/github/Monalika-P/Complete-guide-to-tensorflow-2.0/blob/master/Introduction_to_Tensorflow2.0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Installing tensorflow 2.0**

Command - !pip install tensorflow-gpu==2.0.0-alpha0 


In [11]:
# Importing the libraries
import tensorflow as tf
import numpy as np

In [12]:
# Checking the version
tf.__version__

'2.3.0'

 **Contants**

 **Defining a constant**

In [13]:
tensor = tf.constant([[23,4],[32,5]])

In [14]:
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[23,  4],
       [32,  5]], dtype=int32)>

In [15]:
tensor.shape

TensorShape([2, 2])

**Getting the values of a constant**

In [16]:
tensor.numpy()

array([[23,  4],
       [32,  5]], dtype=int32)

In [17]:
numpy_tensor = np.array([[23,4],[45,8]])

In [18]:
numpy_tensor

array([[23,  4],
       [45,  8]])

In [19]:
tensor_from_numpy = tf.constant(numpy_tensor)

In [20]:
tensor_from_numpy

<tf.Tensor: shape=(2, 2), dtype=int64, numpy=
array([[23,  4],
       [45,  8]])>

**Variable**

**Defining a variable**

In [21]:
tf2_variable = tf.Variable([[1,2,3],[7,8,10]])

In [22]:
tf2_variable

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[ 1,  2,  3],
       [ 7,  8, 10]], dtype=int32)>

**Getting values of variables**

In [23]:
tf2_variable.numpy

<bound method BaseResourceVariable.numpy of <tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[ 1,  2,  3],
       [ 7,  8, 10]], dtype=int32)>>

**Changing a specific variable value**

In [24]:
tf2_variable[0,2].assign(100)

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=int32, numpy=
array([[  1,   2, 100],
       [  7,   8,  10]], dtype=int32)>

**Operations with tensors**

In [25]:
tensor = tf.constant([[23,4],[32,5]])

In [26]:
tensor*2 #Multiplying a scalar with a tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[46,  8],
       [64, 10]], dtype=int32)>

In [27]:
tensor+2 #Adding a scalar to a tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[25,  6],
       [34,  7]], dtype=int32)>

In [28]:
tensor -2 #Subtracting a scalar with a tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[21,  2],
       [30,  3]], dtype=int32)>

In [29]:
tensor/2 #Dividing a scalar by a tensor

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[11.5,  2. ],
       [16. ,  2.5]])>

**Numpy functions on Tensors**

In [30]:
np.square(tensor)

array([[ 529,   16],
       [1024,   25]], dtype=int32)

In [31]:
np.sqrt(tensor)

array([[4.79583152, 2.        ],
       [5.65685425, 2.23606798]])

**Dot Product between two tensors**

In [33]:
np.dot(tensor,tensor)

array([[657, 112],
       [896, 153]], dtype=int32)

**String operations**

In [34]:
string = tf.constant("Hello world")

In [35]:
string

<tf.Tensor: shape=(), dtype=string, numpy=b'Hello world'>

**String operations**

In [36]:
tf.strings.length(string)

<tf.Tensor: shape=(), dtype=int32, numpy=11>

In [38]:
# For decoding
tf.strings.unicode_decode(string,"UTF8")

<tf.Tensor: shape=(11,), dtype=int32, numpy=array([ 72, 101, 108, 108, 111,  32, 119, 111, 114, 108, 100], dtype=int32)>

**Storing arrays to strings**

In [41]:
tf_arrays = tf.constant(["Hayley Marshall","Nicklaus Michelson","Hope Michelson"])

In [42]:
for strings in tf_arrays:
  print(strings)

tf.Tensor(b'Hayley Marshall', shape=(), dtype=string)
tf.Tensor(b'Nicklaus Michelson', shape=(), dtype=string)
tf.Tensor(b'Hope Michelson', shape=(), dtype=string)
